import DashboardCard from "../_components/DashboardCard/DashboardCard";
import styles from "../dashboard.module.css"
import { topCardsData } from "../_staticData/dashboardData";
import { Box, Grid } from "@mui/material";

export const metadata = {
  title: "Provider Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Box sx={{ padding: 2, margin: "5% 15%" }}>
          <Grid container spacing={7}>
            {topCardsData.map((card, index) => (
              <Grid item xs={12} sm={6} md={4} key={index}>
                 <DashboardCard card={card} sx={{ height: "100%" }}/>
              </Grid>
            ))}
          </Grid>
        </Box>
        {children}

      </body>
    </html>
  );
}
