import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './theme.css';
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "sonner";
import {AuthProvider} from "./context/AuthContext"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthProvider>
          <Navbar/>
                  {children}
          <Toaster richColors position="top-right" />
      </AuthProvider>
        
         {/* <div className="container">
                  {children}
        </div> */}
      </body>
    </html>
  );
}
